### ISSUE TITLE
Applying log4j2

### ISSUE THREAD

**Issue by djkeh** [djkeh/bootSecurityJPAExample#8]
Spring Boot uses Logback as its default logger.
This issue is to change it to log4j2.

## TODO

* [ ] Try logging something for logging test (using default logger, logback)
* [ ] Switch logger to log4j2
* [ ] See the differences and compatibility issues
